//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.10 at 04:56:56 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/01903/v1.4.1#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.etsi.uri._01903.v1_4;
